version: "3.1"
services:
  database:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_DB=pp2db"
      - "POSTGRES_USER=dbadmin"
      - "POSTGRES_PASSWORD=admin123"
